alias mit-scheme='/Applications/"MIT:GNU Scheme.app"/Contents/Resources/mit-scheme'
alias clang++='clang++ -std=c++11 -stdlib=libc++'
alias ll='ls -l --color'
alias la='ls -a --color'
alias lla='ls -al --color'
